name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: tar.gz
        filename: 'release.tar.gz'
        exclusions: '*.git* /*node_modules/* .editorconfig'